import { AlarmClock, Baby, Banana, Bath, Bed, Bell, Birdhouse, Book, Carrot, Cat, ChevronDown, Clock, CloudLightning, Coffee, Cone, Crown, CupSoda,
          Dice2, Dog, DollarSign, Donut, Droplet, Drum, Drumstick, Dumbbell, Ear, Egg, Feather, Fish, Footprints, Gamepad, Gem, Ghost, Gift,
          Glasses, Globe, Guitar, Hammer, Hand, Headphones, Heart, Hourglass, House, IceCreamCone, Key, Keyboard, Lamp, Landmark, Laugh,
          Lightbulb, Lock, Magnet, Mail, Martini, Medal, Milk, Moon, Mountain, Music, Nut, Paintbrush, Palette, PartyPopper, Pi, Pickaxe, Pizza,
          Plane, Popcorn, Popsicle, Puzzle, Rabbit, Rainbow, Rose, Ruler, Sailboat, Shell, Soup, Sprout, Star, Sun, Thermometer, Tornado, Volleyball, Zap, type LucideIcon
        } from "lucide-react";

export { ChevronDown, Clock };

export const ICON_MAP: Record<string, LucideIcon> = {
  AlarmClock,
  Baby,
  Banana,
  Bath,
  Bed,
  Bell,
  Birdhouse,
  Book,
  Carrot,
  Cat,
  CloudLightning,
  Coffee,
  Cone,
  Crown,
  CupSoda,
  Dice2,
  Dog,
  DollarSign,
  Donut,
  Droplet,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  Egg,
  Feather,
  Fish,
  Footprints,
  Gamepad,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  Guitar,
  Hammer,
  Hand,
  Headphones,
  Heart,
  Hourglass,
  House,
  IceCreamCone,
  Key,
  Keyboard,
  Lamp,
  Landmark,
  Laugh,
  Lightbulb,
  Lock,
  Magnet,
  Mail,
  Martini,
  Medal,
  Milk,
  Moon,
  Mountain,
  Music,
  Nut,
  Paintbrush,
  Palette,
  PartyPopper,
  Pi,
  Pickaxe,
  Pizza,
  Plane,
  Popcorn,
  Popsicle,
  Puzzle,
  Rabbit,
  Rainbow,
  Rose,
  Ruler,
  Sailboat,
  Shell,
  Soup,
  Sprout,
  Star,
  Sun,
  Thermometer,
  Tornado,
  Volleyball,
  Zap,
};

export const ICON_NAMES = Object.keys(ICON_MAP);
